version: 1
send_anonymous_usage_stats: false
default_environment: dev
environments:
- name: dev
  env:
    DB_LOCATION: /project/data/dev/data.duckdb
- name: test
  env:
    DB_LOCATION: /project/data/test/data.duckdb
- name: prod
  env:
    DB_LOCATION: /project/data/prod/data.duckdb
plugins:
  extractors:
  - name: tap-rest-api-msdk
    variant: widen
    pip_url: tap-rest-api-msdk
    capabilities:
    - state
    - catalog
    - discover
    settings:
    - name: api_url
      kind: string
    - name: next_page_token_path
      kind: string
    - name: pagination_request_style
      kind: string
    - name: pagination_response_style
      kind: string
    - name: pagination_page_size
      kind: integer
    - name: streams
      kind: array
    - name: path
      kind: string
    - name: params
      kind: object
    - name: headers
      kind: object
    - name: records_path
      kind: string
    - name: primary_keys
      kind: array
    - name: replication_key
      kind: string
    - name: except_keys
      kind: array
    - name: num_inference_records
      kind: integer
    config:
      api_url: https://earthquake.usgs.gov/fdsnws
  - name: tap-rest-api-gie
    inherit_from: tap-rest-api-msdk
    config:
      api_url: https://agsi.gie.eu
      headers:
        x-key: $ENV_GIE_XKEY
      params:
        date: $ENV_DATE_GIE
        #date: '2023-02-15'
      stream_maps:
        stg_gie_storage:
          key_hash: md5(config['hash_seed'] + (gasDayStart + code))
          #__alias__: stg_gie_storage_vX
        stg_gie_company:
          key_hash: md5(config['hash_seed'] + (gasDayStart + code))
        stg_gie_country:
          key_hash: md5(config['hash_seed'] + (gasDayStart + code))
        stg_gie_region:
          key_hash: md5(config['hash_seed'] + (gasDayStart + code))
      stream_map_config:
        hash_seed: 01AWZh7A6DzGm6iJZZ2T          
      streams:
      - name: stg_gie_storage
        path: /api
#        headers:
#          x-key: XXX
#        params:
#          date: $ENV_DATE_GIE
#          date: '2022-12-31'          
        primary_keys:
        - code
        - gasDayStart
        records_path: $.data[*].children[*].children[*].children[*]
      - name: stg_gie_company
        path: /api
        primary_keys:
        - code
        - gasDayStart
        records_path: $.data[*].children[*].children[*]
      - name: stg_gie_country
        path: /api
        primary_keys:
        - code
        - gasDayStart
        records_path: $.data[*].children[*] 
      - name: stg_gie_region
        path: /api
        primary_keys:
        - code
        - gasDayStart
        records_path: $.data[*]    
      - name: stg_gie_region_flat
        path: /api
        primary_keys:
        - code
        - gasDayStart
        records_path: $.data[*]                       
    select:
    - '*.*'
  - name: stg_gie_faclist
    inherit_from: tap-rest-api-msdk
    config:
      api_url: https://agsi.gie.eu
      headers:
        x-key: $ENV_GIE_XKEY
      streams:
      - name: stg_gie_faclist
        path: /api/about
      - name: stg_gie_faclist_2
        path: /api/about?show=listing
  - name: stg_usgs
    inherit_from: tap-rest-api-msdk
    config:
      api_url: https://earthquake.usgs.gov/fdsnws
      streams:
      - name: stg_usgs_earthquakes
        params:
          format: geojson
          starttime: '2010-01-01'
#          endtime: '2014-01-02'
          minmagnitude: 6
        path: /event/1/query
        primary_keys:
        - id
        records_path: $.features[*]
        num_inference_records: 200
    select:
    - '*.*'        
  loaders:
  - name: target-duckdb
    pip_url: target-duckdb~=0.4
    config:
      add_metadata_columns: true
      default_target_schema: main
      filepath: $DB_LOCATION
      data_flattening_max_level: 10
  - name: target-duckdb-usgs
    inherit_from: target-duckdb
    config:
      add_metadata_columns: true
      default_target_schema: main
      filepath: $DB_LOCATION
      data_flattening_max_level: 10
      primary_key_required: false
  - name: target-duckdb-try
    inherit_from: target-duckdb
    config:
      add_metadata_columns: true
      #default_target_schema: gie
      default_target_schema: main
      filepath: $DB_LOCATION
      data_flattening_max_level: 10
      primary_key_required: false
  orchestrators:
  - name: airflow
    variant: apache
    pip_url: apache-airflow==2.1.2 --constraint https://raw.githubusercontent.com/apache/airflow/constraints-2.1.2/constraints-${MELTANO__PYTHON_VERSION}.txt
#  transformers:
#  - name: dbt-duckdb
#    variant: jwills
#    pip_url: dbt-core~=1.2.0 dbt-duckdb~=1.2.0
  files:
  - name: files-airflow
    variant: meltano
    pip_url: git+https://github.com/meltano/files-airflow.git --constraint https://raw.githubusercontent.com/apache/airflow/constraints-2.1.2/constraints-${MELTANO__PYTHON_VERSION}.txt
  utilities:
  - name: superset
    variant: apache
    #pip_url: apache-superset==1.5.0 markupsafe==2.0.1 duckdb-engine==0.6.4
    pip_url: apache-superset==2.0.0 flask==2.0.3 werkzeug==2.0.3 jinja2==3.0.1 wtforms==2.3.3
      git+https://github.com/meltano/superset-ext.git@main cryptography==3.4.7 markupsafe==2.0.1 
      duckdb-engine==0.7.0
  - name: dbt-duckdb
    variant: jwills
    #pip_url: dbt-core~=1.3.0 dbt-duckdb~=1.3.0 git+https://github.com/meltano/dbt-ext.git@main
    pip_url: dbt-core~=1.4.0 dbt-duckdb~=1.4.0 git+https://github.com/meltano/dbt-ext.git@main
    commands:
      usgs:
        args: run --select tag:usgs
        description: Runsd dbt USGS (earthquake data) jobs instead of all dbt jobs.
      gie:
        args: run --select tag:gie
jobs:
- name: usgs-to-duckdb-rpt
  tasks:
  - stg_usgs target-duckdb-usgs dbt-duckdb:usgs
schedules:
#- name: USGS-Earthquake
#  interval: 35 */1 * * *
#  extractor: stg_usgs
#  loader: target-duckdb-usgs
#  transform: skip
#  start_date: 2023-01-01 15:40:21.295936
- name: USGS-Earthquake
  interval: 35 */1 * * *
  job: usgs-to-duckdb-rpt
  start_date: 2023-01-01 15:40:21.295936
