version: 2

sources:
  - name: gie_stage
    database: data  
    schema: main 
    loader: Using Meltano, from GIE rest API.
    description: "Gas storage and in/outlfow for EU countries provided by GIE (https://agsi.gie.eu/)."
    freshness: 
      warn_after: {count: 12, period: hour}
      #error_after: {count: 24, period: hour}
    loaded_at_field: _sdc_extracted_at
    tables:
      - name: stg_gie_storage
        description: Source data at SSO/storage facility level.
      - name: stg_gie_company
      - name: stg_gie_country
      - name: stg_gie_region
  - name: usgs_stage
    database: data  
    schema: main  
    loader: Using Meltano, from USGS rest API.
    description: "Earthquake information provided by USGS (https://earthquake.usgs.gov/fdsnws/event/1/)."
    freshness: 
      warn_after: {count: 12, period: hour}
      #error_after: {count: 24, period: hour}
    loaded_at_field: _sdc_extracted_at
    tables:
      - name: stg_usgs_earthquakes
        description: Source earthquake data.
