version: 2

sources:
  - name: gie_stage
    database: data  
    schema: main 
    loader: Using Meltano, from GIE rest API.
    freshness: 
      warn_after: {count: 12, period: hour}
      #error_after: {count: 24, period: hour}
    loaded_at_field: _sdc_extracted_at
    tables:
      - name: stg_gie_storage
      - name: stg_gie_company
      - name: stg_gie_country
      - name: stg_gie_region
  - name: usgs_stage
    database: data  
    schema: main  
    loader: Using Meltano, from GIE rest API.
    freshness: 
      warn_after: {count: 12, period: hour}
      #error_after: {count: 24, period: hour}
    loaded_at_field: _sdc_extracted_at
    tables:
      - name: stg_usgs_earthquakes
